name: Update README from blog feed

on:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

env:
  BLOG_FEED_URL: https://blog.hwooo.life/feed.xml
  BLOG_MAX_ITEMS: 3

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install rss-parser
        run: npm i rss-parser@3.13.0

      - name: Update README
        run: node scripts/update-readme.mjs

      - name: Commit & push changes
        run: |
          if ! git diff --quiet README.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update blog posts in README"
            git push
          else
            echo "No changes to commit."
          fi
